# --- numer of images to process ---
NUM_IMAGES: null

# --- folders ---
INPUT_FOLDER: "data/data_examples/"
OUTPUT_FOLDER: "output"
RGB_FOLDER:
NIR_FOLDER:
MASK_FOLDER:

# --- masking parameters ---
R_MIN_SIZE: 5
B_MIN_SIZE: 5
H_MIN_SIZE: 150
R_SELEM_CLOSE: 3
B_SELEM_CLOSE: 3
H_SELEM_CLOSE: 2
MAX_SIZE: 1200

# --- adaptive mask parameters ---
MIN_SIZE_WEAK: 5
MIN_SIZE_STRONG: 50

# --- adaptive false positives cleanup ---
FP_RATIO_THR: 0.4
MIN_SIZE_STRONG: 120
SELEM_CLOSE_STRONG: 5

# --- channels thresholds ---
R_STD_MULT: 0.1
B_STD_MULT: 0.1
H_STD_MULT: 0.1
NIR_STD_MULT: 0.5

# --- mask h-black threshold ---
H_BLACK_RATIO: 0.9
